INSERT INTO PELDANY VALUES (1, 'NodeView', 'string, string', 'private',5);
INSERT INTO PELDANY VALUES (2, 'MyNode', '', 'public',3);
INSERT INTO PELDANY VALUES (3, 'MyNode', 'string, int', 'private',8);
INSERT INTO PELDANY VALUES (4, 'NodeView2', 'string, int', 'protected',5);
INSERT INTO PELDANY VALUES (5, 'NodeView', 'string, string', 'private',3);
INSERT INTO PELDANY VALUES (6, 'Test', 'real, string', 'private',1);
INSERT INTO PELDANY VALUES (7, 'MyNode', 'real, int', 'private',4);
INSERT INTO PELDANY VALUES (8, 'Test, 'string, int', 'public',7);
INSERT INTO PELDANY VALUES (9, 'NodeView2', 'int, string', 'private',6);
INSERT INTO PELDANY VALUES (10, 'NodeView2', 'real, real', 'private',3);
INSERT INTO PELDANY VALUES (11, 'NodeView2', 'string', 'protected',1);
INSERT INTO PELDANY VALUES (12, 'MyNode', 'real', 'public',9);
INSERT INTO PELDANY VALUES (13, 'MyNode', 'int', 'private',3);
INSERT INTO PELDANY VALUES (14, 'NodeView', '', 'private',2);
INSERT INTO PELDANY VALUES (15, 'NodeView', 'string', 'protected',4);
INSERT INTO PELDANY VALUES (16, 'Test', '', 'private',5);
INSERT INTO PELDANY VALUES (17, 'Model', 'string', 'public',7);
INSERT INTO PELDANY VALUES (18, 'Model', 'string, string', 'private',3);
