-- CTAS SELECT
-- GRANT SELECT ON CIKK TO PUBLIC;
/*
CREATE TABLE CIKK AS
SELECT *
FROM VZOLI.CIKK;
*/

-- 1
SELECT CIKK.CKOD, CNEV
FROM CIKK NATURAL JOIN (SELECT distinct CKOD
FROM SZALLIT S, SZALLITO SO
WHERE S.SZKOD = SO.SZKOD
AND TELEPHELY = 'Pecs') lek
WHERE CIKK.CKOD = lek.CKOD
;

-- 2
SELECT distinct C.CKOD, CNEV
FROM SZALLIT S, SZALLITO SO, CIKK C
WHERE S.SZKOD = SO.SZKOD
AND S.CKOD = C.CKOD
AND TELEPHELY = 'Pecs'
;

-- cikknevenként elõforduló legtöbb CKOD
SELECT MIN(COUNT(*)) kvaélet...
FROM CIKK
GROUP BY CNEV
HAVING COUNT(*) = (SELECT MAC (COUNT(*))
                    FROM CIKK
                    GROUP BY CNEV)
;

-- 3 (1-es komplemense)