/*
összetett riport dolgozó tábla alaján
összjövedelem telephelyenként -> explicit kurzor
utolsó sor - vállalatszintű "összesen" felirattal vállalati összjövedelem
*/

-- vállalatszintű
SELECT TELEPHELY, SUM(FIZETES + NVL(JUTALEK, 0))
FROM DOLGOZO, OSZTALY
WHERE DOLGOZO.OAZON = OSZTALY.OAZON
GROUP BY TELEPHELY;

-- egész
SET SERVEROUTPUT ON
DECLARE
    L_JOV NUMBER;
    CURSOR C_THJOV IS
        SELECT TELEPHELY, SUM(FIZETES + NVL(JUTALEK, 0)) JOV
        FROM DOLGOZO, OSZTALY
        WHERE DOLGOZO.OAZON = OSZTALY.OAZON
        GROUP BY TELEPHELY;
    L_SOR C_THJOV%ROWTYPE;
BEGIN
    OPEN C_THJOV;
        LOOP
            FETCH C_THJOV INTO L_SOR;
            EXIT WHEN C_THJOV%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(L_SOR.TELEPHELY || ': ' || L_SOR.JOV);
        END LOOP;
    CLOSE C_THJOV;
    SELECT SUM(FIZETES + NVL(JUTALEK, 0))
    INTO L_JOV
    FROM DOLGOZO; -- összjövhez kell
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('VALLALAT:' || L_JOV);
END;
/
/*
NEW YORK: 8750
CHICAGO: 11600
DALLAS: 10875

VALLALAT:32025
*/

/* fvbe*/
-- fv
CREATE OR REPLACE FUNCTION F_SJOV RETURN NUMBER
IS
L_JOV NUMBER;
BEGIN
    SELECT SUM(FIZETES + NVL(JUTALEK, 0))
    INTO L_JOV
    FROM DOLGOZO;
    RETURN L_JOV;
END;

-- plsql
SET SERVEROUTPUT ON
DECLARE
    L_JOV NUMBER;
    CURSOR C_THJOV IS
        SELECT TELEPHELY, SUM(FIZETES + NVL(JUTALEK, 0)) JOV
        FROM DOLGOZO, OSZTALY
        WHERE DOLGOZO.OAZON = OSZTALY.OAZON
        GROUP BY TELEPHELY;
    L_SOR C_THJOV%ROWTYPE;
BEGIN
    OPEN C_THJOV;
        LOOP
            FETCH C_THJOV INTO L_SOR;
            EXIT WHEN C_THJOV%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(L_SOR.TELEPHELY || ': ' || L_SOR.JOV);
        END LOOP;
    CLOSE C_THJOV;
    L_JOV := F_SJOV;
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('VALLALAT:' || L_JOV);
END;
/
/*
NEW YORK: 8750
CHICAGO: 11600
DALLAS: 10875

VALLALAT:32025
*/

-- test
SELECT F_SJOV FROM DUAL

-- fv telephelyenkénti sum jöv
CREATE OR REPLACE FUNCTION F_SJOVTH(TH VARCHAR2) RETURN NUMBER
IS
L_JOV NUMBER;
BEGIN
    SELECT NVL(SUM(FIZETES + NVL(JUTALEK, 0)), 0)
    INTO L_JOV
    FROM DOLGOZO NATURAL JOIN OSZTALY
    WHERE TH = TELEPHELY; -- TELEPHELY = TH; nope
    RETURN L_JOV;
END;

-- test
SELECT F_SJOVTH('DALLAS') FROM DUAL;

-- forral
SET SERVEROUTPUT ON;
BEGIN
    FOR SOR IN (
        SELECT DISTINCT TELEPHELY
        FROM OSZTALY
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(SOR.TELEPHELY || ': ' || F_SJOVTH(SOR.TELEPHELY));
    END LOOP;
END;
/*
NEW YORK: 8750
CHICAGO: 11600
BOSTON: 0
DALLAS: 10875
*/



-- pm-es kurzorral
SET SERVEROUTPUT ON
DECLARE
    CURSOR C_THJOVP(TH VARCHAR2) IS
        SELECT TELEPHELY, SUM(FIZETES + NVL(JUTALEK, 0)) JOV
        FROM DOLGOZO, OSZTALY
        WHERE DOLGOZO.OAZON = OSZTALY.OAZON
        GROUP BY TELEPHELY
        HAVING TELEPHELY = TH;
    L_SOR C_THJOVP%ROWTYPE;
BEGIN
    FOR SOR IN (
        SELECT TELEPHELY TEL -- DISTINCT is jó
        FROM OSZTALY
    )
    LOOP
        FOR SOR2 IN C_THJOVP(SOR.TEL)
            LOOP
                DBMS_OUTPUT.PUT_LINE(SOR.TEL || ': ' || SOR2.JOV);
            END LOOP;
    END LOOP;
END;
/*
NEW YORK: 8750
DALLAS: 10875
CHICAGO: 11600
*/