@echo off 
set CP=jdbc/lib/ojdbc6.jar
set CP=%CP%;jlib/orai18n-collation.jar
set CP=%CP%;jlib/orai18n-mapping.jar
set CP=%CP%;jlib/orai18n-servlet.jar
set CP=%CP%;jlib/orai18n-utility.jar
set CP=%CP%;jlib/orai18n.jar
set CP=%CP%;sqldeveloper/extensions/oracle.sqldeveloper.jar
set CP=%CP%;sqldeveloper/lib/oracle.sqldeveloper.utils.jar
set CP=%CP%;sqldeveloper/lib/oracle.sqldeveloper.utils-nodeps.jar
set CP=%CP%;sqldeveloper/lib/itextpdf-5.1.2.jar
set CP=%CP%;sqldeveloper/lib/poi-3.8-20120326
set CP=%CP%;modules/oracle.javatools_11.1.1/javatools-nodeps.jar
set CP=%CP%;sqldeveloper/lib/jline-0.9.9.jar
set CP=%CP%;ide/lib/javatools.jar
set CP=%CP%;ide/extensions/oracle.ide.jar
set CP=%CP%;jlib/jdev-cm.jar
set CP=%CP%;ide/lib/dbapi.jar
