/*
-- összes adat
SELECT *
FROM DOLGOZO
WHERE OAZON = 10 OR OAZON = 20; -- 10-es és 20-as osztályon dolgozók

SELECT *
FROM DOLGOZO
WHERE OAZON = 10
UNION
SELECT *
FROM DOLGOZO
WHERE OAZON = 20; -- OR helyett UNION

-- csak a nevek
SELECT DNEV
FROM DOLGOZO
WHERE OAZON = 10
UNION
SELECT DNEV
FROM DOLGOZO
WHERE OAZON = 20;

-- nevek oszlop felirata "DOLGOZÓNÉV"
SELECT DNEV AS DOLGOZÓNÉV
FROM DOLGOZO
WHERE OAZON = 10
UNION
SELECT DNEV
FROM DOLGOZO
WHERE OAZON = 20;

-- oszlopfelirat több szóban
SELECT DNEV AS Dolgozó Neve -- Dolgozó Név LOL melyik név dolgozik?
FROM DOLGOZO
WHERE OAZON = 10
UNION
SELECT DNEV
FROM DOLGOZO
WHERE OAZON = 20; -- hiba
*/

SELECT DNEV AS "Dolgozó Neve"
FROM DOLGOZO
WHERE OAZON = 10
UNION
SELECT DNEV
FROM DOLGOZO
WHERE OAZON = 20;