-- 11. pontosan 2féle

SELECT distinct s1.NEV
FROM SZERET s1, SZERET s2
WHERE s1.NEV = s2.NEV AND s1.GYUMOLCS != s2.GYUMOLCS
INTERSECT
SELECT distinct NEV
FROM SZERET
MINUS
SELECT distinct s1.NEV
FROM SZERET s1, SZERET s2, SZERET s3
WHERE s1.NEV = s2.NEV AND s1.NEV = s3.NEV 
AND s1.GYUMOLCS != s2.GYUMOLCS AND s1.GYUMOLCS != s3.GYUMOLCS AND s2.GYUMOLCS != s3.GYUMOLCS;