<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2013 (x64) - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:n1="osdm_ad" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link n1 sps xbrldi xbrli xlink xs xsd xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2013 (x64) (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=7"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:2cm; margin-right:2cm; margin-top:2cm; margin-bottom:2cm } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body style="empty-cells:show; font-family:Tahoma; font-size:xx-small; text-align:left; vertical-align:top; word-wrap:break-word; ">
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:root">
						<br/>
						<center>
							<xsl:for-each select="n1:ReportCaption">
								<span style="font-size:medium; font-weight:bold; ">
									<xsl:apply-templates/>
								</span>
							</xsl:for-each>
						</center>
						<br/>
						<br/>
						<table style="width:20cm; " border="0" cellpadding="3" cellspacing="0">
							<xsl:variable name="altova:CurrContextGrid_0" select="."/>
							<tbody>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Design Name</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:DesignName) &gt; 0">
														<xsl:for-each select="n1:DesignName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Version Date</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:VersionDate) &gt; 0">
														<xsl:for-each select="n1:VersionDate">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Version Comment</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:VersionComment">
													<xsl:for-each select="n1:VersionCommentDetails">
														<xsl:for-each select="n1:VersionCommentRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="count(n1:VersionComment/n1:VersionCommentDetails/n1:VersionCommentRow) &gt; 0">
														<xsl:for-each select="n1:VersionComment">
															<xsl:for-each select="n1:VersionCommentDetails">
																<xsl:for-each select="n1:VersionCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:choose>
													<xsl:when test="count(n1:VersionComment/n1:VersionCommentDetails/n1:VersionCommentRow) &gt; 0">
														<xsl:for-each select="n1:VersionComment">
															<xsl:for-each select="n1:VersionCommentDetails">
																<xsl:for-each select="n1:VersionCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise/>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:VersionComment">
													<xsl:for-each select="n1:VersionCommentDetails">
														<xsl:for-each select="n1:VersionCommentRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:VersionComment">
													<xsl:for-each select="n1:VersionCommentDetails">
														<xsl:for-each select="n1:VersionCommentRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
							</tbody>
						</table>
						<xsl:for-each select="n1:DomainsCollection">
							<xsl:for-each select="n1:DomainDetails">
								<br class="altova-page-break" clear="all"/>
								<table style="width:15cm; " border="0" cellpadding="3" cellspacing="0">
									<xsl:variable name="altova:CurrContextGrid_1" select="."/>
									<tbody>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Domain Name</xsl:text>
												</span>
											</td>
											<td style="background-color:#a5e7ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:11cm; ">
												<h1>
													<a>
														<xsl:attribute name="name">
															<xsl:value-of select="n1:DomainName"/>
														</xsl:attribute>
														<xsl:choose>
															<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																<xsl:for-each select="n1:DomainName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																<xsl:choose>
																	<xsl:when test="string-length(n1:DomainName) &gt; 0">
																		<xsl:for-each select="n1:DomainName">
																			<span style="font-size:xx-small; ">
																				<xsl:apply-templates/>
																			</span>
																		</xsl:for-each>
																	</xsl:when>
																	<xsl:otherwise>
																		<span>
																			<xsl:text>&#160;</xsl:text>
																		</span>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																<xsl:for-each select="n1:DomainName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																<xsl:for-each select="n1:DomainName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																<xsl:for-each select="n1:DomainName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
														</xsl:choose>
													</a>
												</h1>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Synonyms</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:Synonyms">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:Synonyms) &gt; 0">
																<xsl:for-each select="n1:Synonyms">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:Synonyms">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:Synonyms">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:Synonyms">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Data Type</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:DataType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:DataType) &gt; 0">
																<xsl:for-each select="n1:DataType">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:DataType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:DataType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:DataType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Logical Type</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:LogicalType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:LogicalType) &gt; 0">
																<xsl:for-each select="n1:LogicalType">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:LogicalType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:LogicalType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:LogicalType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Unit Of Measure</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:UnitOfMeasure">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:UnitOfMeasure) &gt; 0">
																<xsl:for-each select="n1:UnitOfMeasure">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:UnitOfMeasure">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:UnitOfMeasure">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:UnitOfMeasure">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Default Value</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:DefaultValue">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:DefaultValue) &gt; 0">
																<xsl:for-each select="n1:DefaultValue">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:DefaultValue">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:DefaultValue">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:DefaultValue">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Comments</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:DomainComment">
															<xsl:for-each select="n1:DomainCommentDetails">
																<xsl:for-each select="n1:DomainCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="count(n1:DomainComment/n1:DomainCommentDetails/n1:DomainCommentRow) &gt; 0">
																<xsl:for-each select="n1:DomainComment">
																	<xsl:for-each select="n1:DomainCommentDetails">
																		<xsl:for-each select="n1:DomainCommentRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:choose>
															<xsl:when test="count(n1:DomainComment/n1:DomainCommentDetails/n1:DomainCommentRow) &gt; 0">
																<xsl:for-each select="n1:DomainComment">
																	<xsl:for-each select="n1:DomainCommentDetails">
																		<xsl:for-each select="n1:DomainCommentRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise/>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:DomainComment">
															<xsl:for-each select="n1:DomainCommentDetails">
																<xsl:for-each select="n1:DomainCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:DomainComment">
															<xsl:for-each select="n1:DomainCommentDetails">
																<xsl:for-each select="n1:DomainCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
									</tbody>
								</table>
								<xsl:if test="count( n1:ConstraintsCollection )">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Constraints</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0" width="100%">
										<xsl:variable name="altova:CurrContextGrid_2" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr style="text-align:center; ">
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; ">
													<span>
														<xsl:text>Details</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:ConstraintsCollection">
												<xsl:for-each select="n1:ConstraintDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; ">
															<xsl:if test="count( n1:RangesCollection )">
																<table style="width:24.5cm; " border="0" cellpadding="3" cellspacing="0">
																	<xsl:variable name="altova:CurrContextGrid_3" select="."/>
																	<thead style="background-color:#d9f5ff; ">
																		<tr>
																			<th colspan="3" style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:3cm; ">
																				<span>
																					<xsl:text>Ranges</xsl:text>
																				</span>
																			</th>
																		</tr>
																		<tr>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:3cm; ">
																				<span>
																					<xsl:text>Begin Value</xsl:text>
																				</span>
																			</th>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:3cm; ">
																				<span>
																					<xsl:text>End Value</xsl:text>
																				</span>
																			</th>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:18.5cm; ">
																				<span>
																					<xsl:text>Description</xsl:text>
																				</span>
																			</th>
																		</tr>
																	</thead>
																	<tbody>
																		<xsl:for-each select="n1:RangesCollection">
																			<xsl:for-each select="n1:RangeDetails">
																				<tr>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:right; width:3cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:RangeBeginValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="string-length(n1:RangeBeginValue) &gt; 0">
																										<xsl:for-each select="n1:RangeBeginValue">
																											<xsl:apply-templates/>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:for-each select="n1:RangeBeginValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:RangeBeginValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:RangeBeginValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:right; width:3cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:RangeEndValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="string-length(n1:RangeEndValue) &gt; 0">
																										<xsl:for-each select="n1:RangeEndValue">
																											<xsl:apply-templates/>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:for-each select="n1:RangeEndValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:RangeEndValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:RangeEndValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:18.5cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:RangeShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="string-length(n1:RangeShortDescription) &gt; 0">
																										<xsl:for-each select="n1:RangeShortDescription">
																											<xsl:apply-templates/>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:for-each select="n1:RangeShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:RangeShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:RangeShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																				</tr>
																			</xsl:for-each>
																		</xsl:for-each>
																	</tbody>
																</table>
															</xsl:if>
															<xsl:if test="count( n1:ValueListsCollection ) != 0">
																<table style="width:24.5cm; " border="0" cellpadding="3" cellspacing="0">
																	<xsl:variable name="altova:CurrContextGrid_4" select="."/>
																	<thead style="background-color:#d9f5ff; ">
																		<tr>
																			<th colspan="2" style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:3cm; ">
																				<span>
																					<xsl:text>Value List</xsl:text>
																				</span>
																			</th>
																		</tr>
																		<tr>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:3cm; ">
																				<span>
																					<xsl:text>Value</xsl:text>
																				</span>
																			</th>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:21.5cm; ">
																				<span>
																					<xsl:text>Description</xsl:text>
																				</span>
																			</th>
																		</tr>
																	</thead>
																	<tbody>
																		<xsl:for-each select="n1:ValueListsCollection">
																			<xsl:for-each select="n1:ValueListDetails">
																				<tr>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:3cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:VLValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="string-length(n1:VLValue) &gt; 0">
																										<xsl:for-each select="n1:VLValue">
																											<xsl:apply-templates/>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:for-each select="n1:VLValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:VLValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:VLValue">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:21.5cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:VLShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="string-length(n1:VLShortDescription) &gt; 0">
																										<xsl:for-each select="n1:VLShortDescription">
																											<xsl:apply-templates/>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:for-each select="n1:VLShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:VLShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:VLShortDescription">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																				</tr>
																			</xsl:for-each>
																		</xsl:for-each>
																	</tbody>
																</table>
															</xsl:if>
															<xsl:if test="count( n1:CheckConstraintsCollection ) != 0">
																<table style="width:24.5cm; " border="0" cellpadding="3" cellspacing="0">
																	<xsl:variable name="altova:CurrContextGrid_5" select="."/>
																	<thead style="background-color:#d9f5ff; ">
																		<tr>
																			<th colspan="2" style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:21.5cm; ">
																				<span>
																					<xsl:text>Check Constraint</xsl:text>
																				</span>
																			</th>
																		</tr>
																		<tr>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:21.5cm; ">
																				<span>
																					<xsl:text>Text</xsl:text>
																				</span>
																			</th>
																			<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:3cm; ">
																				<span>
																					<xsl:text>DB Type</xsl:text>
																				</span>
																			</th>
																		</tr>
																	</thead>
																	<tbody>
																		<xsl:for-each select="n1:CheckConstraintsCollection">
																			<xsl:for-each select="n1:CheckConstraintDetails">
																				<tr>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:21.5cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:CheckConstraintText">
																									<xsl:for-each select="n1:CheckConstraintTextDetails">
																										<xsl:for-each select="n1:CheckConstraintTextRow">
																											<xsl:apply-templates/>
																											<br/>
																										</xsl:for-each>
																									</xsl:for-each>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="count(n1:CheckConstraintText/n1:CheckConstraintTextDetails/n1:CheckConstraintTextRow) &gt; 0">
																										<xsl:for-each select="n1:CheckConstraintText">
																											<xsl:for-each select="n1:CheckConstraintTextDetails">
																												<xsl:for-each select="n1:CheckConstraintTextRow">
																													<xsl:apply-templates/>
																													<br/>
																												</xsl:for-each>
																											</xsl:for-each>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:choose>
																									<xsl:when test="count(n1:CheckConstraintText/n1:CheckConstraintTextDetails/n1:CheckConstraintTextRow) &gt; 0">
																										<xsl:for-each select="n1:CheckConstraintText">
																											<xsl:for-each select="n1:CheckConstraintTextDetails">
																												<xsl:for-each select="n1:CheckConstraintTextRow">
																													<xsl:apply-templates/>
																													<br/>
																												</xsl:for-each>
																											</xsl:for-each>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise/>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:CheckConstraintText">
																									<xsl:for-each select="n1:CheckConstraintTextDetails">
																										<xsl:for-each select="n1:CheckConstraintTextRow">
																											<xsl:apply-templates/>
																											<br/>
																										</xsl:for-each>
																									</xsl:for-each>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:CheckConstraintText">
																									<xsl:for-each select="n1:CheckConstraintTextDetails">
																										<xsl:for-each select="n1:CheckConstraintTextRow">
																											<xsl:apply-templates/>
																											<br/>
																										</xsl:for-each>
																									</xsl:for-each>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																					<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:3cm; ">
																						<xsl:choose>
																							<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																								<xsl:for-each select="n1:DatabaseType">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																								<xsl:choose>
																									<xsl:when test="string-length(n1:DatabaseType) &gt; 0">
																										<xsl:for-each select="n1:DatabaseType">
																											<xsl:apply-templates/>
																										</xsl:for-each>
																									</xsl:when>
																									<xsl:otherwise>
																										<span>
																											<xsl:text>&#160;</xsl:text>
																										</span>
																									</xsl:otherwise>
																								</xsl:choose>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																								<xsl:for-each select="n1:DatabaseType">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																								<xsl:for-each select="n1:DatabaseType">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																								<xsl:for-each select="n1:DatabaseType">
																									<xsl:apply-templates/>
																								</xsl:for-each>
																							</xsl:when>
																						</xsl:choose>
																					</td>
																				</tr>
																			</xsl:for-each>
																		</xsl:for-each>
																	</tbody>
																</table>
															</xsl:if>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:TablesCollection )">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Used In Tables</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_6" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:8cm; ">
													<span>
														<xsl:text>Model Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:8.5cm; ">
													<span>
														<xsl:text>Table Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:8.5cm; ">
													<span>
														<xsl:text>Column Name</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:TablesCollection">
												<xsl:for-each select="n1:TableDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:8cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:ModelName) &gt; 0">
																			<xsl:for-each select="n1:ModelName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:8.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:TableName) &gt; 0">
																			<xsl:for-each select="n1:TableName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:8.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:ColumnName) &gt; 0">
																			<xsl:for-each select="n1:ColumnName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:EntitiesCollection)">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Used In Entities</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_7" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:12.5cm; ">
													<span>
														<xsl:text>Entity Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:12.5cm; ">
													<span>
														<xsl:text>Attribute Name</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:EntitiesCollection">
												<xsl:for-each select="n1:EntityDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:12.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:EntityName) &gt; 0">
																			<xsl:for-each select="n1:EntityName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:12.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:AttributeName) &gt; 0">
																			<xsl:for-each select="n1:AttributeName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
