<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2013 (x64) - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:n1="osdm_a_st" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link n1 sps xbrldi xbrli xlink xs xsd xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2013 (x64) (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=7"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:2cm; margin-right:2cm; margin-top:2cm; margin-bottom:2cm } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body style="empty-cells:show; font-family:Tahoma; font-size:xx-small; text-align:left; vertical-align:top; word-wrap:break-word; ">
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:root">
						<br/>
						<center>
							<xsl:for-each select="n1:ReportCaption">
								<span style="font-size:medium; font-weight:bold; ">
									<xsl:apply-templates/>
								</span>
							</xsl:for-each>
						</center>
						<br/>
						<br/>
						<table style="width:20cm; " border="0" cellpadding="3" cellspacing="0">
							<xsl:variable name="altova:CurrContextGrid_0" select="."/>
							<tbody>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Design Name</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:DesignName) &gt; 0">
														<xsl:for-each select="n1:DesignName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:DesignName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Version Date</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:VersionDate) &gt; 0">
														<xsl:for-each select="n1:VersionDate">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:VersionDate">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Version Comment</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:VersionComment">
													<xsl:for-each select="n1:VersionCommentDetails">
														<xsl:for-each select="n1:VersionCommentRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="count(n1:VersionComment/n1:VersionCommentDetails/n1:VersionCommentRow) &gt; 0">
														<xsl:for-each select="n1:VersionComment">
															<xsl:for-each select="n1:VersionCommentDetails">
																<xsl:for-each select="n1:VersionCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:choose>
													<xsl:when test="count(n1:VersionComment/n1:VersionCommentDetails/n1:VersionCommentRow) &gt; 0">
														<xsl:for-each select="n1:VersionComment">
															<xsl:for-each select="n1:VersionCommentDetails">
																<xsl:for-each select="n1:VersionCommentRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise/>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:VersionComment">
													<xsl:for-each select="n1:VersionCommentDetails">
														<xsl:for-each select="n1:VersionCommentRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:VersionComment">
													<xsl:for-each select="n1:VersionCommentDetails">
														<xsl:for-each select="n1:VersionCommentRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
										<span>
											<xsl:text>Model Name</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:16cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:ModelName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:ModelName) &gt; 0">
														<xsl:for-each select="n1:ModelName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:ModelName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:ModelName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:ModelName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
							</tbody>
						</table>
						<xsl:for-each select="n1:STCollection">
							<xsl:for-each select="n1:STDetails">
								<br/>
								<br class="altova-page-break" clear="all"/>
								<table style="width:15cm; " border="0" cellpadding="3" cellspacing="0">
									<xsl:variable name="altova:CurrContextGrid_1" select="."/>
									<tbody>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Structured Type Name</xsl:text>
												</span>
											</td>
											<td style="background-color:#a5e7ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:11cm; ">
												<h1>
													<a>
														<xsl:attribute name="name">
															<xsl:value-of select="n1:STName"/>
														</xsl:attribute>
														<xsl:choose>
															<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																<xsl:for-each select="n1:STName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																<xsl:choose>
																	<xsl:when test="string-length(n1:STName) &gt; 0">
																		<xsl:for-each select="n1:STName">
																			<span style="font-size:xx-small; ">
																				<xsl:apply-templates/>
																			</span>
																		</xsl:for-each>
																	</xsl:when>
																	<xsl:otherwise>
																		<span>
																			<xsl:text>&#160;</xsl:text>
																		</span>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																<xsl:for-each select="n1:STName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																<xsl:for-each select="n1:STName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																<xsl:for-each select="n1:STName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
														</xsl:choose>
													</a>
												</h1>
											</td>
										</tr>
										<tr>
											<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
												<span>
													<xsl:text>Super Type</xsl:text>
												</span>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:STSuperType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:STSuperType) &gt; 0">
																<xsl:for-each select="n1:STSuperType">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:STSuperType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:STSuperType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:STSuperType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
									</tbody>
								</table>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:if test="count( n1:DescriptionNotes )">
									<br/>
									<xsl:for-each select="n1:DescriptionNotes">
										<table style="width:20cm; " border="0" cellpadding="3" cellspacing="0">
											<xsl:variable name="altova:CurrContextGrid_2" select="."/>
											<tbody>
												<tr>
													<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
														<span>
															<xsl:text>Description</xsl:text>
														</span>
													</td>
													<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:16cm; ">
														<xsl:choose>
															<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																<xsl:for-each select="n1:Description">
																	<xsl:for-each select="n1:DescriptionDetails">
																		<xsl:for-each select="n1:DescriptionRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																<xsl:choose>
																	<xsl:when test="count(n1:Description/n1:DescriptionDetails/n1:DescriptionRow) &gt; 0">
																		<xsl:for-each select="n1:Description">
																			<xsl:for-each select="n1:DescriptionDetails">
																				<xsl:for-each select="n1:DescriptionRow">
																					<xsl:apply-templates/>
																					<br/>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:when>
																	<xsl:otherwise>
																		<span>
																			<xsl:text>&#160;</xsl:text>
																		</span>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																<xsl:choose>
																	<xsl:when test="count(n1:Description/n1:DescriptionDetails/n1:DescriptionRow) &gt; 0">
																		<xsl:for-each select="n1:Description">
																			<xsl:for-each select="n1:DescriptionDetails">
																				<xsl:for-each select="n1:DescriptionRow">
																					<xsl:apply-templates/>
																					<br/>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:when>
																	<xsl:otherwise/>
																</xsl:choose>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																<xsl:for-each select="n1:Description">
																	<xsl:for-each select="n1:DescriptionDetails">
																		<xsl:for-each select="n1:DescriptionRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																<xsl:for-each select="n1:Description">
																	<xsl:for-each select="n1:DescriptionDetails">
																		<xsl:for-each select="n1:DescriptionRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
														</xsl:choose>
													</td>
												</tr>
												<tr>
													<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; font-weight:bold; width:4cm; ">
														<span>
															<xsl:text>Notes</xsl:text>
														</span>
													</td>
													<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:16cm; ">
														<xsl:choose>
															<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																<xsl:for-each select="n1:Notes">
																	<xsl:for-each select="n1:NotesDetails">
																		<xsl:for-each select="n1:NoteRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																<xsl:choose>
																	<xsl:when test="count(n1:Notes/n1:NotesDetails/n1:NoteRow) &gt; 0">
																		<xsl:for-each select="n1:Notes">
																			<xsl:for-each select="n1:NotesDetails">
																				<xsl:for-each select="n1:NoteRow">
																					<xsl:apply-templates/>
																					<br/>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:when>
																	<xsl:otherwise>
																		<span>
																			<xsl:text>&#160;</xsl:text>
																		</span>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																<xsl:choose>
																	<xsl:when test="count(n1:Notes/n1:NotesDetails/n1:NoteRow) &gt; 0">
																		<xsl:for-each select="n1:Notes">
																			<xsl:for-each select="n1:NotesDetails">
																				<xsl:for-each select="n1:NoteRow">
																					<xsl:apply-templates/>
																					<br/>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:when>
																	<xsl:otherwise/>
																</xsl:choose>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																<xsl:for-each select="n1:Notes">
																	<xsl:for-each select="n1:NotesDetails">
																		<xsl:for-each select="n1:NoteRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																<xsl:for-each select="n1:Notes">
																	<xsl:for-each select="n1:NotesDetails">
																		<xsl:for-each select="n1:NoteRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
														</xsl:choose>
													</td>
												</tr>
											</tbody>
										</table>
									</xsl:for-each>
								</xsl:if>
								<xsl:if test="count( n1:DiagramsCollection)">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Used In Diagrams</xsl:text>
									</span>
									<br/>
									<table style="width:8cm; " border="0" cellpadding="3" cellspacing="0" width="100%">
										<xsl:variable name="altova:CurrContextGrid_3" select="."/>
										<tbody>
											<tr style="background-color:#d9f5ff; ">
												<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:8cm; ">
													<span>
														<xsl:text>Diagram Name</xsl:text>
													</span>
												</td>
											</tr>
											<xsl:for-each select="n1:DiagramsCollection">
												<tr>
													<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:8cm; ">
														<xsl:for-each select="n1:DiagramName">
															<a>
																<xsl:choose>
																	<xsl:when test="not(string(.))">
																		<xsl:attribute name="href">
																			<xsl:text>#</xsl:text>
																		</xsl:attribute>
																	</xsl:when>
																	<xsl:when test="substring(string(.), 1, 1) = '#'">
																		<xsl:attribute name="href">
																			<xsl:value-of select="."/>
																		</xsl:attribute>
																	</xsl:when>
																	<xsl:otherwise>
																		<xsl:attribute name="href">
																			<xsl:if test="substring(string(.), 2, 1) = ':'">
																				<xsl:text>file:///</xsl:text>
																			</xsl:if>
																			<xsl:value-of select="translate(string(.), '&#x5c;', '/')"/>
																		</xsl:attribute>
																	</xsl:otherwise>
																</xsl:choose>
																<span>
																	<xsl:value-of select="substring-after( . ,&apos;/&apos;)"/>
																</span>
																<br/>
															</a>
														</xsl:for-each>
													</td>
												</tr>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:AttributesCollection)">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Attributes</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_4" select="."/>
										<thead style="background-color:#d9f5ff; text-align:center; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; vertical-align:middle; width:1cm; ">
													<span>
														<xsl:text>No</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; vertical-align:middle; width:15cm; ">
													<span>
														<xsl:text>Attribute Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; vertical-align:middle; width:1cm; ">
													<span>
														<xsl:text>M</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; vertical-align:middle; width:4.0cm; ">
													<span>
														<xsl:text>Data Type</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; vertical-align:middle; width:1cm; ">
													<span>
														<xsl:text>DT </xsl:text>
													</span>
													<br/>
													<span>
														<xsl:text>kind</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; vertical-align:middle; width:3cm; ">
													<span>
														<xsl:text>Domain Name</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:AttributesCollection">
												<xsl:for-each select="n1:AttributeDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:right; vertical-align:top; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:Sequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:Sequence) &gt; 0">
																			<xsl:for-each select="n1:Sequence">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:Sequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:Sequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:Sequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; vertical-align:top; width:15cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:AttributeName) &gt; 0">
																			<xsl:for-each select="n1:AttributeName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; vertical-align:top; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:M">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:M) &gt; 0">
																			<xsl:for-each select="n1:M">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:M">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:M">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:M">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; vertical-align:top; width:4.0cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:DataType">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:DataType) &gt; 0">
																			<xsl:for-each select="n1:DataType">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:DataType">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:DataType">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:DataType">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; vertical-align:top; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:DataTypeKind">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:DataTypeKind) &gt; 0">
																			<xsl:for-each select="n1:DataTypeKind">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:DataTypeKind">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:DataTypeKind">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:DataTypeKind">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; vertical-align:top; width:3cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:DomainName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:DomainName) &gt; 0">
																			<xsl:for-each select="n1:DomainName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:DomainName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:DomainName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:DomainName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:AttributesCommentsCollection )">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Attributes Comments</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_5" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
													<span>
														<xsl:text>No</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:6cm; ">
													<span>
														<xsl:text>Attribute Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:9cm; ">
													<span>
														<xsl:text>Description</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:9cm; ">
													<span>
														<xsl:text>Notes</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:AttributesCommentsCollection">
												<xsl:for-each select="n1:AttributeCommentsDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:right; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeCommentsSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:AttributeCommentsSequence) &gt; 0">
																			<xsl:for-each select="n1:AttributeCommentsSequence">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:AttributeCommentsSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeCommentsSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeCommentsSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:6cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeCommentsName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:AttributeCommentsName) &gt; 0">
																			<xsl:for-each select="n1:AttributeCommentsName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:AttributeCommentsName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeCommentsName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeCommentsName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:9cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeDescription">
																		<xsl:for-each select="n1:AttributeDescriptionDetails">
																			<xsl:for-each select="n1:AttributeDescriptionRow">
																				<xsl:apply-templates/>
																				<br/>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="count(n1:AttributeDescription/n1:AttributeDescriptionDetails/n1:AttributeDescriptionRow) &gt; 0">
																			<xsl:for-each select="n1:AttributeDescription">
																				<xsl:for-each select="n1:AttributeDescriptionDetails">
																					<xsl:for-each select="n1:AttributeDescriptionRow">
																						<xsl:apply-templates/>
																						<br/>
																					</xsl:for-each>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:choose>
																		<xsl:when test="count(n1:AttributeDescription/n1:AttributeDescriptionDetails/n1:AttributeDescriptionRow) &gt; 0">
																			<xsl:for-each select="n1:AttributeDescription">
																				<xsl:for-each select="n1:AttributeDescriptionDetails">
																					<xsl:for-each select="n1:AttributeDescriptionRow">
																						<xsl:apply-templates/>
																						<br/>
																					</xsl:for-each>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise/>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeDescription">
																		<xsl:for-each select="n1:AttributeDescriptionDetails">
																			<xsl:for-each select="n1:AttributeDescriptionRow">
																				<xsl:apply-templates/>
																				<br/>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeDescription">
																		<xsl:for-each select="n1:AttributeDescriptionDetails">
																			<xsl:for-each select="n1:AttributeDescriptionRow">
																				<xsl:apply-templates/>
																				<br/>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:9cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeNotes">
																		<xsl:for-each select="n1:AttributeNotesDetails">
																			<xsl:for-each select="n1:AttributeNoteRow">
																				<xsl:apply-templates/>
																				<br/>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="count(n1:AttributeNotes/n1:AttributeNotesDetails/n1:AttributeNoteRow) &gt; 0">
																			<xsl:for-each select="n1:AttributeNotes">
																				<xsl:for-each select="n1:AttributeNotesDetails">
																					<xsl:for-each select="n1:AttributeNoteRow">
																						<xsl:apply-templates/>
																						<br/>
																					</xsl:for-each>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:choose>
																		<xsl:when test="count(n1:AttributeNotes/n1:AttributeNotesDetails/n1:AttributeNoteRow) &gt; 0">
																			<xsl:for-each select="n1:AttributeNotes">
																				<xsl:for-each select="n1:AttributeNotesDetails">
																					<xsl:for-each select="n1:AttributeNoteRow">
																						<xsl:apply-templates/>
																						<br/>
																					</xsl:for-each>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise/>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeNotes">
																		<xsl:for-each select="n1:AttributeNotesDetails">
																			<xsl:for-each select="n1:AttributeNoteRow">
																				<xsl:apply-templates/>
																				<br/>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeNotes">
																		<xsl:for-each select="n1:AttributeNotesDetails">
																			<xsl:for-each select="n1:AttributeNoteRow">
																				<xsl:apply-templates/>
																				<br/>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:MethodsCollection )">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Methods</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_6" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
													<span>
														<xsl:text>No</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:5cm; ">
													<span>
														<xsl:text>Method Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
													<span>
														<xsl:text>C</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
													<span>
														<xsl:text>O</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:5cm; ">
													<span>
														<xsl:text>Overriden Method</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:5cm; ">
													<span>
														<xsl:text>Return Value</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:7cm; ">
													<span>
														<xsl:text>Parameters</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:MethodsCollection">
												<xsl:for-each select="n1:MethodDetails">
													<tr style="vertical-align:top; ">
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:right; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:MethodSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodSequence) &gt; 0">
																			<xsl:for-each select="n1:MethodSequence">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:MethodSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:MethodSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:MethodSequence">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:MethodName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodName) &gt; 0">
																			<xsl:for-each select="n1:MethodName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:MethodName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:MethodName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:MethodName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:MethodConstructor">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodConstructor) &gt; 0">
																			<xsl:for-each select="n1:MethodConstructor">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:MethodConstructor">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:MethodConstructor">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:MethodConstructor">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:MethodOverriding">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodOverriding) &gt; 0">
																			<xsl:for-each select="n1:MethodOverriding">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:MethodOverriding">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:MethodOverriding">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:MethodOverriding">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:MethodOverridenMethod">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodOverridenMethod) &gt; 0">
																			<xsl:for-each select="n1:MethodOverridenMethod">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:MethodOverridenMethod">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:MethodOverridenMethod">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:MethodOverridenMethod">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodReturnValue) &gt; 0">
																			<xsl:for-each select="n1:MethodReturnValue">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:MethodReturnValue) &gt; 0">
																			<xsl:for-each select="n1:MethodReturnValue">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:MethodReturnValue">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:MethodReturnValue">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:MethodReturnValue">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:7cm; ">
															<xsl:choose>
																<xsl:when test="count(n1:MethodParametersCollection )">
																	<br/>
																	<table style="text-align:center; " border="0" cellpadding="3" cellspacing="0">
																		<xsl:variable name="altova:CurrContextGrid_7" select="."/>
																		<thead style="background:#d9f5ff; ">
																			<tr>
																				<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:3.3cm; ">
																					<span>
																						<xsl:text>Name</xsl:text>
																					</span>
																				</th>
																				<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:3.3cm; ">
																					<span>
																						<xsl:text>Type</xsl:text>
																					</span>
																				</th>
																			</tr>
																		</thead>
																		<tbody>
																			<xsl:for-each select="n1:MethodParametersCollection">
																				<xsl:for-each select="n1:MethodParameterDetails">
																					<tr>
																						<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:3.3cm; ">
																							<xsl:choose>
																								<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																									<xsl:for-each select="n1:ParameterName">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																									<xsl:choose>
																										<xsl:when test="string-length(n1:ParameterName) &gt; 0">
																											<xsl:for-each select="n1:ParameterName">
																												<xsl:apply-templates/>
																											</xsl:for-each>
																										</xsl:when>
																										<xsl:otherwise>
																											<span>
																												<xsl:text>&#160;</xsl:text>
																											</span>
																										</xsl:otherwise>
																									</xsl:choose>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																									<xsl:for-each select="n1:ParameterName">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																									<xsl:for-each select="n1:ParameterName">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																									<xsl:for-each select="n1:ParameterName">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																							</xsl:choose>
																						</td>
																						<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:3.3cm; ">
																							<xsl:choose>
																								<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																									<xsl:for-each select="n1:ParameterType">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																									<xsl:choose>
																										<xsl:when test="string-length(n1:ParameterType) &gt; 0">
																											<xsl:for-each select="n1:ParameterType">
																												<xsl:apply-templates/>
																											</xsl:for-each>
																										</xsl:when>
																										<xsl:otherwise>
																											<span>
																												<xsl:text>&#160;</xsl:text>
																											</span>
																										</xsl:otherwise>
																									</xsl:choose>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																									<xsl:for-each select="n1:ParameterType">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																									<xsl:for-each select="n1:ParameterType">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																								<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																									<xsl:for-each select="n1:ParameterType">
																										<xsl:apply-templates/>
																									</xsl:for-each>
																								</xsl:when>
																							</xsl:choose>
																						</td>
																					</tr>
																				</xsl:for-each>
																			</xsl:for-each>
																		</tbody>
																	</table>
																</xsl:when>
																<xsl:otherwise>
																	<span>
																		<xsl:text>&#160;</xsl:text>
																	</span>
																</xsl:otherwise>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:TablesCollection )">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Used In Tables</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_8" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:8cm; ">
													<span>
														<xsl:text>Model Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:8.5cm; ">
													<span>
														<xsl:text>Table Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:8.5cm; ">
													<span>
														<xsl:text>Column Name</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:TablesCollection">
												<xsl:for-each select="n1:TableDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; vertical-align:top; width:8cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:ModelName) &gt; 0">
																			<xsl:for-each select="n1:ModelName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:ModelName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; vertical-align:top; width:8.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:TableName) &gt; 0">
																			<xsl:for-each select="n1:TableName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:TableName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; vertical-align:top; width:8.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:ColumnName) &gt; 0">
																			<xsl:for-each select="n1:ColumnName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:ColumnName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
								<xsl:if test="count( n1:EntitiesCollection)">
									<br/>
									<span style="font-size:xx-small; font-style:italic; ">
										<xsl:text>Used In Entities</xsl:text>
									</span>
									<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
										<xsl:variable name="altova:CurrContextGrid_9" select="."/>
										<thead style="background-color:#d9f5ff; ">
											<tr>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:12.5cm; ">
													<span>
														<xsl:text>Entity Name</xsl:text>
													</span>
												</th>
												<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; text-align:center; width:12.5cm; ">
													<span>
														<xsl:text>Attribute Name</xsl:text>
													</span>
												</th>
											</tr>
										</thead>
										<tbody>
											<xsl:for-each select="n1:EntitiesCollection">
												<xsl:for-each select="n1:EntityDetails">
													<tr>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; width:12.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:EntityName) &gt; 0">
																			<xsl:for-each select="n1:EntityName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:EntityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
														<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:12.5cm; ">
															<xsl:choose>
																<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
																	<xsl:choose>
																		<xsl:when test="string-length(n1:AttributeName) &gt; 0">
																			<xsl:for-each select="n1:AttributeName">
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<span>
																				<xsl:text>&#160;</xsl:text>
																			</span>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
																<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
																	<xsl:for-each select="n1:AttributeName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:when>
															</xsl:choose>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</tbody>
									</table>
								</xsl:if>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
