-- pt 1.8 meghaladja fõnök fizujának 80%át

SELECT D1.DNEV "F?nök azonosítója", D2.DNEV "Dolgozó neve"
FROM DOLGOZO D1, DOLGOZO D2
WHERE D1.DKOD = D2.FONOKE
AND D2.FIZETES + D2.JUTALEK > 0.8*(D1.FIZETES + NVL(D1.JUTALEK, 0))
AND D2.JUTALEK IS NOT NULL
ORDER BY 1,2;