DROP TABLE LineItems;
DROP TABLE StockItems;
DROP TABLE Orders;
DROP TABLE Costumers;

CREATE TABLE LineItems (
    LineNo NUMBER NOT NULL,
    PONo NUMBER NOT NULL,
    StockNo NUMBER NOT NULL,
    Quantity NUMBER,
    Discount NUMBER,
    CONSTRAINT LINEITEMS_PRIMARY_KEY PRIMARY KEY (LineNo),
    CONSTRAINT LINEITEMS_PRIMARY_KEY PRIMARY KEY (PONo)
);
INSERT INTO LineItems VALUES (1, 1, 1, 1, 30);

CREATE TABLE StockItems (
    StockNo NUMBER NOT NULL,
    Description VARCHAR2(1000),
    Price NUMBER,
    CONSTRAINT STOCKITEMS_PRIMARY_KEY PRIMARY KEY (StockNo),
    CONSTRAINT STOCKITEMS_FOREIGN_KEY FOREIGN KEY (StockNo) REFERENCES LineItems (StockNo)
);
INSERT INTO StockItems VALUES (1, 'description', 1000);

CREATE TABLE Orders (
    PONo NUMBER NOT NULL,
    CustNo NUMBER NOT NULL,
    OrderDate DATE,
    ShipDate DATE,
    ToStreet VARCHAR2(20),
    ToCity VARCHAR2(20),
    ToState CHAR,
    ToZip VARCHAR2(20),
    CONSTRAINT ORDERS_PRIMARY_KEY PRIMARY KEY (PONo),
    CONSTRAINT ORDERS_FOREIGN_KEY FOREIGN KEY (PONo) REFERENCES LineItems (PONo)
);
INSERT INTO Orders VALUES (1, 5, '10-MAY-2017', '17-MAY-2017', 'Street', 'City', 'S', 'Zip');

CREATE TABLE Costumers (
    CustNo NUMBER NOT NULL,
    CustName VARCHAR2(30),
    Street VARCHAR2(20),
    City VARCHAR2(20),
    State CHAR,
    Zip VARCHAR2(20),
    Phone VARCHAR2(15),
    CONSTRAINT COSTUMERS_PRIMARY_KEY PRIMARY KEY (CustNo),
    CONSTRAINT COSTUMERS_FOREIGN_KEY FOREIGN KEY (CustNo) REFERENCES Orders (CustNo)
);
INSERT INTO Costumers VALUES (5, 'Costumer Name', 'Street', 'City', 'S', 'Zip', '06-20-123-4567');

COMMIT;

GRANT SELECT ON LineItems TO PUBLIC;
GRANT SELECT ON StockItems TO PUBLIC;
GRANT SELECT ON Orders TO PUBLIC;
GRANT SELECT ON Costumers TO PUBLIC;